### ISSUE TITLE
Reproduce the results

### ISSUE THREAD

**Issue by jjongs97** [955374/OPSNet#1]
I cannot reproduce the results in the paper, do you have any suggestions?

**Comment by 955374** [comment]
Hi, experimental results may be affected by lots of factors, such as hardware, system environment, etc. This is a temporary repo for journal reviewing, please contact me if you have further concerns.

**Comment by jjongs97** [comment]
I have conducted experiments on the van and cyclist categories, and my results of 47.2/54.3 and 39.9/50.1 respectively differ significantly from the results reported in the paper.

**Comment by 955374** [comment]
Due to the insufficient training samples, the results may vary greatly across different runs for the Van and Cyc class. It seems as if the model has not reached the convergence.
